# Generated by Django 5.1 on 2024-09-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Find_Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
